// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -source=main.go -destination=mock_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// Mockrunner is a mock of runner interface.
type Mockrunner struct {
	ctrl     *gomock.Controller
	recorder *MockrunnerMockRecorder
	isgomock struct{}
}

// MockrunnerMockRecorder is the mock recorder for Mockrunner.
type MockrunnerMockRecorder struct {
	mock *Mockrunner
}

// NewMockrunner creates a new mock instance.
func NewMockrunner(ctrl *gomock.Controller) *Mockrunner {
	mock := &Mockrunner{ctrl: ctrl}
	mock.recorder = &MockrunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrunner) EXPECT() *MockrunnerMockRecorder {
	return m.recorder
}

// RunClaude mocks base method.
func (m *Mockrunner) RunClaude(args []string) (runResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunClaude", args)
	ret0, _ := ret[0].(runResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunClaude indicates an expected call of RunClaude.
func (mr *MockrunnerMockRecorder) RunClaude(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunClaude", reflect.TypeOf((*Mockrunner)(nil).RunClaude), args)
}

// Mockwaiter is a mock of waiter interface.
type Mockwaiter struct {
	ctrl     *gomock.Controller
	recorder *MockwaiterMockRecorder
	isgomock struct{}
}

// MockwaiterMockRecorder is the mock recorder for Mockwaiter.
type MockwaiterMockRecorder struct {
	mock *Mockwaiter
}

// NewMockwaiter creates a new mock instance.
func NewMockwaiter(ctrl *gomock.Controller) *Mockwaiter {
	mock := &Mockwaiter{ctrl: ctrl}
	mock.recorder = &MockwaiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwaiter) EXPECT() *MockwaiterMockRecorder {
	return m.recorder
}

// WaitUntil mocks base method.
func (m *Mockwaiter) WaitUntil(ctx context.Context, target time.Time) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitUntil", ctx, target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WaitUntil indicates an expected call of WaitUntil.
func (mr *MockwaiterMockRecorder) WaitUntil(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitUntil", reflect.TypeOf((*Mockwaiter)(nil).WaitUntil), ctx, target)
}
